//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradeSection()
        {
            this.StudentTraits = new HashSet<StudentTrait>();
            this.StudentEnrollments = new HashSet<StudentEnrollment>();
        }
    
        public int GradeSectionCode { get; set; }
        public string GradeLevel { get; set; }
        public string Section { get; set; }
        public bool Deactivated { get; set; }
        public string HomeRoomTeacherId { get; set; }
        public Nullable<int> HomeRoomNumber { get; set; }
        public Nullable<int> Class { get; set; }
        public string SY { get; set; }
    
        public virtual GradeLevel GradeLevel1 { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTrait> StudentTraits { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentEnrollment> StudentEnrollments { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
