//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Schedule1 { get; set; }
        public Nullable<int> StudentAssignmentID { get; set; }
        public string TimeslotCode { get; set; }
    
        public virtual SubjectAssignment SubjectAssignment { get; set; }
        public virtual Timeslot Timeslot { get; set; }
    }
}
