//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentEnrollment()
        {
            this.StudentAssessments = new HashSet<StudentAssessment>();
            this.StudentSubjects = new HashSet<StudentSubject>();
            this.StudentTraits = new HashSet<StudentTrait>();
        }
    
        public string StudentSY { get; set; }
        public string StudentId { get; set; }
        public string GradeLevel { get; set; }
        public Nullable<int> GradeSectionCode { get; set; }
        public Nullable<bool> Dismissed { get; set; }
        public int StudentEnrollmentsID { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public string Stat { get; set; }
        public string SY { get; set; }
    
        public virtual GradeSection GradeSection { get; set; }
        public virtual ScholarshipDiscount ScholarshipDiscount { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSubject> StudentSubjects { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTrait> StudentTraits { get; set; }
    }
}
