//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssessment
    {
        public int StudentAssessmentId { get; set; }
        public string StudentSY { get; set; }
        public Nullable<int> FeeID { get; set; }
        public Nullable<int> DiscountId { get; set; }
    
        public virtual Fee Fee { get; set; }
        public virtual ScholarshipDiscount ScholarshipDiscount { get; set; }
        public virtual StudentEnrollment StudentEnrollment { get; set; }
    }
}
