//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherEducationalBackground
    {
        public string TeacherId { get; set; }
        public int TEBId { get; set; }
        public string EducLevel { get; set; }
        public string NameOfSchool { get; set; }
        public Nullable<System.DateTime> TEBYearFrom { get; set; }
        public Nullable<System.DateTime> TEBYearTo { get; set; }
        public string Course { get; set; }
        public string HonorsReceived { get; set; }
        public bool Deactivated { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
