//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherEligibility
    {
        public string TeacherId { get; set; }
        public int EligibilityId { get; set; }
        public string Eligibility { get; set; }
        public string Rating { get; set; }
        public Nullable<System.DateTime> DateOfExam { get; set; }
        public string PlaceOfExam { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
