//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingSeminar
    {
        public string TeacherId { get; set; }
        public int TSID { get; set; }
        public string Title { get; set; }
        public string AreaOfTraining { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<double> NoOfHours { get; set; }
        public string ConductedBy { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
