//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public string TeacherId { get; set; }
        public int WEId { get; set; }
        public Nullable<System.DateTime> WorkExpFrom { get; set; }
        public Nullable<System.DateTime> WorkExpTo { get; set; }
        public string Position { get; set; }
        public string CompanyName { get; set; }
        public Nullable<double> MonthlySalary { get; set; }
        public string StatusOfEmployment { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
